#!/usr/bin/env bash
# script to transfer file

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE 100.26.213.98 ubuntu PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$ubuntu@100.26.213.98":~/
