#!/usr/bin/env bash
# Configures Nginx for 301 redirect

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Configure redirect
sed -i '/388388-web-01;/a \    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
