#!/bin/bash
# Script that sets the port 80

# Ensure directories and files exist
mkdir -p /etc/nginx/sites-enabled
mkdir -p /etc/nginx/sites-available
touch /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
if command -v service &> /dev/null; then
    service nginx restart
elif command -v systemctl &> /dev/null; then
    systemctl restart nginx
else
    echo "Unable to restart Nginx. Please restart it manually."
fi
