#!/usr/bin/env bash
#Install UFW
sudo apt-get update
sudo apt-get install ufw
#Set the default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing
#Allow the required TCP ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
#Enable the firewall
sudo ufw enable
#Check the status and rules
sudo ufw status verbose
#Here's a summary of the UFW commands you should include in your answer file
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
