#!/usr/bin/env bash
sudo echo "net/ipv4/ip_forward=1" >> /etc/ufw/sysctl.conf
sudo sysctl -p

*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT

# Don't delete these required lines, otherwise there will be errors
*filter

sudo ufw disable
sudo ufw enable
